### creates new patient entity
POST http://localhost:4004/patients
Content-Type: application/json

{
  "name": "kafkaTest1",
  "email": "kafka_test@example.com",
  "address": "123 main street",
  "dateOfBirth": "1999-10-22",
  "registeredDate": "2024-11-28"
}
